import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme'
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import { Bounce } from 'react-toastify';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import Header from "@/app/(frontend)/components/Header";
import Footer from "@/app/(frontend)/components/Footer";


const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});

export const metadata = {
  title: "KD Property Developments",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="KD Property Development" />
      </head>
      <body className={`${roboto.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
          <ToastContainer
            position="bottom-left"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
            <CssBaseline />
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
